#!/bin/bash
# SPDX-FileCopyrightText: The kubectl-gather authors
# SPDX-License-Identifier: Apache-2.0
# oc adm must-gather adapter for running kubectl-gather.

base="/must-gather"

mkdir -p "$base"

printf "gather\n$(kubectl-gather --version)\n" > "$base/version"

kubectl-gather --directory "$base" "$@"
