# SPDX-FileCopyrightText: The kubectl-gather authors
# SPDX-License-Identifier: Apache-2.0

---
name: Test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  lint:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest

  build-matrix:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create build tag
        run: git tag latest
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - name: Build binary
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make

  container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create build tag
        run: git tag latest
      - name: Setup multi-arch podman
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static podman
          podman version
      - name: Make container
        run: make container
